import { PrismaClient } from '../../.prisma/backend-client';

const prisma = new PrismaClient();

export enum ChainTypeEnum {
  All = -1,
  Bitcoin = 0,
  Ethereum = 1,
  Polygon = 2,
  Solana = 3,
  Optimisum = 4,
  Tron = 5,
  Ton = 6,
  Avalanche = 7,
  Bsc = 8,
  XLayer = 9,
  Sui = 10,
}

export async function backendSeedProd(config: Record<string, any>) {
  await clearTable();
  await addDefaultChains();
  await addDefaultNode();
  await addDefaultToken();
}

export async function clearTable() {
  await prisma.$connect();
  await prisma.node.deleteMany();
  await prisma.token.deleteMany();
  await prisma.chain.deleteMany();
}

export async function addDefaultChains() {
  await prisma.$connect();

  // Create chain records
  const chains = [
    {
      chain_id: '1',
      wallet_type: ChainTypeEnum.Ethereum,
      chain_name: 'Ethereum',
      chain_icon: 'https://download.imimo.xyz/token/ETH.png',
      status_type: 1,
      sort: ChainTypeEnum.Ethereum,
    },
    {
      chain_id: '0',
      wallet_type: ChainTypeEnum.Bitcoin,
      chain_name: 'Bitcoin',
      chain_icon: 'https://download.imimo.xyz/token/BTC.png',
      status_type: 1,
      sort: ChainTypeEnum.Bitcoin,
    },
    {
      chain_id: '137',
      wallet_type: ChainTypeEnum.Polygon,
      chain_name: 'Polygon',
      chain_icon: 'https://download.imimo.xyz/token/POL.png',
      status_type: 1,
      sort: ChainTypeEnum.Polygon,
    },
    {
      chain_id: '728126428',
      chain_name: 'TRON',
      wallet_type: ChainTypeEnum.Tron,
      chain_icon: 'https://download.imimo.xyz/token/TRX.png',
      status_type: 1,
      sort: ChainTypeEnum.Tron,
    },
    {
      chain_id: '-1',
      chain_name: 'TON',
      wallet_type: ChainTypeEnum.Ton,
      chain_icon: 'https://download.imimo.xyz/token/TON.png',
      status_type: 1,
      sort: ChainTypeEnum.Ton,
    },
    {
      chain_id: '5426',
      wallet_type: ChainTypeEnum.Solana,
      chain_name: 'Solana',
      chain_icon: 'https://download.imimo.xyz/token/SOL.png',
      status_type: 1,
      sort: ChainTypeEnum.Solana,
    },
    {
      chain_id: '43114',
      chain_name: 'Avalanche C',
      wallet_type: ChainTypeEnum.Avalanche,
      chain_icon: 'https://download.imimo.xyz/token/AVAX.png',
      status_type: 1,
      sort: ChainTypeEnum.Avalanche,
    },
    {
      chain_id: '56',
      wallet_type: ChainTypeEnum.Bsc,
      chain_name: 'BNB Smart Chain',
      chain_icon: 'https://download.imimo.xyz/token/BNB.png',
      status_type: 1,
      sort: ChainTypeEnum.Bsc,
    },
    {
      chain_id: '196',
      wallet_type: ChainTypeEnum.XLayer,
      chain_name: 'X layer',
      chain_icon: 'https://download.imimo.xyz/token/OKB.png',
      status_type: 1,
      sort: ChainTypeEnum.XLayer,
    },
    {
      chain_id: '10',
      wallet_type: ChainTypeEnum.Optimisum,
      chain_name: 'OP Mainnet',
      chain_icon: 'https://download.imimo.xyz/token/OP.png',
      status_type: 1,
      sort: ChainTypeEnum.Optimisum,
    },
    {
      chain_id: '101',
      wallet_type: ChainTypeEnum.Sui,
      chain_name: 'SUI',
      chain_icon: 'https://download.imimo.xyz/token/SUI.png',
      status_type: 1,
      sort: ChainTypeEnum.Sui,
    },
  ];

  await prisma.chain.createMany({ data: chains });
  await prisma.$disconnect();
}

async function addDefaultNode() {
  await prisma.$connect();

  // Create chain records
  const nodes = [
    {
      chain_id: '1',
      node_url: 'https://eth.llamarpc.com',
    },
    {
      chain_id: '1',
      node_url: 'https://rpc.mevblocker.io',
    },
    {
      chain_id: '1',
      node_url: 'https://ethereum-rpc.publicnode.com',
    },
    {
      chain_id: '1',
      node_url: 'https://eth.public-rpc.com',
    },
    {
      chain_id: '0',
      node_url: 'bitcoin.aranguren.org:50001',
    },
    {
      chain_id: '137',
      node_url: 'https://polygon.llamarpc.com',
    },
    {
      chain_id: '137',
      node_url: 'https://endpoints.omniatech.io/v1/matic/mainnet/public',
    },
    {
      chain_id: '728126428',
      node_url: 'https://rpc.ankr.com/tron_jsonrpc',
    },
    {
      chain_id: '728126428',
      node_url: 'https://api.trongrid.io/jsonrpc',
    },
    {
      chain_id: '-1',
      node_url: 'https://ton.org/global.config.json',
    },
    {
      chain_id: '10',
      node_url: 'https://mainnet.optimism.io',
    },
    {
      chain_id: '10',
      node_url: 'https://optimism.gateway.tenderly.com',
    },
    {
      chain_id: '10',
      node_url: 'https://mainnet.optimism.io',
    },
    {
      chain_id: '196',
      node_url: 'https://rpc.xlayer.tech',
    },
    {
      chain_id: '196',
      node_url: 'https://xlayerrpc.okx.com',
    },
    {
      chain_id: '101',
      node_url: 'https://fullnode.mainnet.sui.io',
    },
    {
      chain_id: '56',
      node_url: 'https://binance.llamarpc.com',
    },
    {
      chain_id: '43114',
      node_url: 'https://api.avax.network/ext/bc/C/rpc',
    },
    {
      chain_id: '5426',
      node_url: 'https://api.mainnet-beta.solana.com',
    },
  ];

  await prisma.node.createMany({ data: nodes });
  await prisma.$disconnect();
}

async function addDefaultToken() {
  await prisma.$connect();
  // Create chain records
  const tokens = [
    {
      chain_id: '0',
      token_symbol: 'BTC',
      token_name: 'BTC',
      is_native: true,
      coin_market_cap_id: 1,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/BTC.png',
    },
    {
      chain_id: '1',
      token_symbol: 'ETH',
      token_name: 'ETH',
      is_native: true,
      coin_market_cap_id: 1027,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/ETH.png',
    },
    {
      chain_id: '1',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '1',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '1',
      token_symbol: 'BNB',
      token_name: 'BNB',
      is_native: false,
      coin_market_cap_id: 1839,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xb8c77482e45f1f44de1745f52c74426c631bdd52',
      token_icon: 'https://download.imimo.xyz/token/BNB.png',
    },
    {
      chain_id: '1',
      token_symbol: 'WBTC',
      token_name: 'Wrapped BTC',
      is_native: false,
      coin_market_cap_id: 1,
      token_decimals: 8,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '137',
      token_symbol: 'POL',
      token_name: 'POL',
      is_native: true,
      coin_market_cap_id: 28321,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/POL.png',
    },
    {
      chain_id: '137',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '137',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '728126428',
      token_symbol: 'TRX',
      token_name: 'TRX',
      is_native: true,
      coin_market_cap_id: 1958,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/TRX.png',
    },
    {
      chain_id: '728126428',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '728126428',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '728126428',
      token_symbol: 'ETH',
      token_name: 'Ethereum',
      is_native: false,
      coin_market_cap_id: 1027,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF',
      token_icon: 'https://download.imimo.xyz/token/ETH.png',
    },
    {
      chain_id: '-1',
      token_symbol: 'TON',
      token_name: 'TON',
      is_native: true,
      coin_market_cap_id: 11419,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/TON.png',
    },
    {
      chain_id: '-1',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '5426',
      token_symbol: 'SOL',
      token_name: 'SOL',
      is_native: true,
      coin_market_cap_id: 5426,
      token_decimals: 9,
      default_subscribe: 1,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/SOL.png',
    },
    {
      chain_id: '5426',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '5426',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '43114',
      token_symbol: 'AVAX',
      token_name: 'AVAX',
      is_native: true,
      coin_market_cap_id: 5805,
      token_decimals: 18,
      default_subscribe: 0,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/AVAX.png',
    },
    {
      chain_id: '43114',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '43114',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '43114',
      token_symbol: 'WBTC',
      token_name: 'Wrapped BTC',
      is_native: false,
      coin_market_cap_id: 1,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: 'https://download.imimo.xyz/token/WBTC.png',
      token_icon: 'https://download.imimo.xyz/token/WBTC.png',
    },
    {
      chain_id: '56',
      token_symbol: 'BNB',
      token_name: 'BNB',
      is_native: true,
      coin_market_cap_id: 1839,
      token_decimals: 18,
      default_subscribe: 0,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/BNB.png',
    },
    {
      chain_id: '56',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '56',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x55d398326f99059ff775485246999027b3197955',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '56',
      token_symbol: 'MKR',
      token_name: 'Maker',
      is_native: false,
      coin_market_cap_id: 1518,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x5f0da599bb2cccfcf6fdfd7d81743b6020864350',
      token_icon: 'https://download.imimo.xyz/token/MKR.png',
    },
    {
      chain_id: '56',
      token_symbol: 'ETH',
      token_name: 'Ethereum Token',
      is_native: false,
      coin_market_cap_id: 1027,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x2170ed0880ac9a755fd29b2688956bd959f933f8',
      token_icon: 'https://download.imimo.xyz/token/ETH.png',
    },
    {
      chain_id: '196',
      token_symbol: 'OKB',
      token_name: 'OKB',
      is_native: true,
      coin_market_cap_id: 3897,
      token_decimals: 18,
      default_subscribe: 0,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/OKB.png',
    },
    {
      chain_id: '196',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x1e4a5963abfd975d8c9021ce480b42188849d41d',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '196',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x74b7f16337b8972027f6196a17a631ac6de26d22',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '196',
      token_symbol: 'WBTC',
      token_name: 'Wrapped BTC',
      is_native: false,
      coin_market_cap_id: 1,
      token_decimals: 8,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0xea034fb02eb1808c2cc3adbc15f447b93cbe08e1',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '10',
      token_symbol: 'OP',
      token_name: 'OP',
      is_native: true,
      coin_market_cap_id: 11840,
      token_decimals: 18,
      default_subscribe: 0,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/OP.png',
    },
    {
      chain_id: '10',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x94b008aa00579c1307b0ef2c499ad98a8ce58e58',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '10',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x0b2c639c533813f4aa9d7837caf62653d097ff85',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '10',
      token_symbol: 'UNI',
      token_name: 'Uniswap',
      is_native: false,
      coin_market_cap_id: 7083,
      token_decimals: 18,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address: '0x6fd9d7ad17242c41f7131d257212c54a0e816691',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
    {
      chain_id: '101',
      token_symbol: 'SUI',
      token_name: 'SUI',
      is_native: true,
      coin_market_cap_id: 20947,
      token_decimals: 9,
      default_subscribe: 0,
      is_multiple_chain: false,
      token_icon: 'https://download.imimo.xyz/token/SUI.png',
    },
    {
      chain_id: '101',
      token_symbol: 'USDT',
      token_name: 'Tether USD',
      is_native: false,
      coin_market_cap_id: 825,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address:
        '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
      token_icon: 'https://download.imimo.xyz/token/USDT.png',
    },
    {
      chain_id: '101',
      token_symbol: 'USDC',
      token_name: 'USD Coin',
      is_native: false,
      coin_market_cap_id: 3408,
      token_decimals: 6,
      default_subscribe: 1,
      is_multiple_chain: true,
      contract_address:
        '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::coin::COIN',
      token_icon: 'https://download.imimo.xyz/token/USDC.png',
    },
  ];

  await prisma.token.createMany({ data: tokens });
  await prisma.$disconnect();
}
